#/usr/bin/env bash

all: README.md

README.md: guessinggame.sh
	echo "## The Unix Workbench Course Peer-Graded Assignment" > README.md
	echo "*by Johns Hopkins University on [coursera.org](https://www.coursera.org/).*" >> README.md
	echo "\\" >> README.md	
	echo "**Description**: make a program called guessinggame.sh. This Bash program is a guessing game where the user tries to guess the number of files in the current directory. The program prompts the user for guesses, provides feedback if the guess is incorrect (whether it's too low or too high), and congratulates the user when they guess correctly. It continues to prompt the user until they make the correct guess." >> README.md
	echo "\\" >> README.md
	echo -n "**Make date**: " >> README.md
	date >> README.md
	echo "\\" >> README.md
	echo -n "**Number of lines in guessinggame.sh:** " >> README.md
	wc -l guessinggame.sh | egrep -o "[0-9]+" >> README.md
	echo "" >> README.md
clean:
	rm README.md
